id: I5ED0CECE
default_language: en
source: https://www.lotsawahouse.org
initial_creation_type: web_scrap
imported: 2023-01-04 11:28:50.604145
last_modified: 2023-01-04 11:28:50.604162
source_metadata:
  collections:
  - Alak Zenkar Rinpoche
  - Works of Tibetan Masters
bases:
  76E6:
    title: Prayer for the Long Life of Alak Zenkar Rinpoche
    base_file: 76E6.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
